# Configuration file for the attacks

model_architecture: "ast" # Which model to attack
model_pretrained_weights: "/home/vtheiou/adversarial_paper/audio-adversarial-attacks/pretrained_models/audioset_10_10_0.4593.pth" # Pretrained weights

# Algorithm Hyperparameters

algorithm: "pso" # or DE
algorithm_hyperparameters: { "initial_particles": 35, "max_iters": 20, "max_inertia_w": 0.9, "min_inertia_w": 0.1, "memory_w": 0.3, "information_w": 1.2, "perturbation_ratio": 0.5 }
# algorithm_hyperparameters: {  "pop_size": 10,"iter": 10,"F": 1.2,"cr": 0.9, "perturbation_ratio": 0.5 }
SNR_norm: 10

# Data Related Variables
data_path: "/data/audioset/validation_set/valid_wav" # Abs Path to data containing wav files
true_labels: "/home/vtheiou/adversarial_paper/audio-adversarial-attacks/ontologies/test_labels.json" # Abs Path containing the true labels in json format
hypercategory_mapping: "/home/vtheiou/adversarial_paper/audio-adversarial-attacks/ontologies/hypercategory_from_ontology.json" # [Optional] Abs Path of hypercategory mapping in json format

# Logging Variables
log_path: "logs/" # Relative Path to project's directory to store the logs
log_file: "log_filename" # Filename of the log file / Should be descriptive to the current experiment / Current Date will be appended at the end.

# Attack Related Variables
objective_function: "simple_minimization" # Objective function to be used
verbosity: True # Control the verbosity of the algorithm
