# Configuration file for the attacks

model_architecture: "beats" # Which model to attack
model_pretrained_weights: "path_to_pt_file.pt" # Pretrained weights

# Algorithm Hyperparameters

algorithm: "PSO" # or DE
algorithm_hyperparameters: { "initial_particles": 35, "max_iters": 20, "max_inertia_w": 0.9, "min_inertia_w": 0.1, "memory_w": 0.3, "information_w": 1.2, "perturbation_ratio": 0.5 }

# Data Related Variables
data_path: "path_to_data_wavs" # Abs Path to data containing wav files
true_labels: "path_to_true_labels" # Abs Path containing the true labels in json format
hypercategory_mapping: Null # [Optional] Abs Path of hypercategory mapping in json format

# Logging Variables
log_path: "logs/" # Relative Path to project's directory to store the logs
log_file: "log_filename" # Filename of the log file / Should be descriptive to the current experiment / Current Date will be appended at the end.

# Attack Related Variables
objective_function: "simple_minimization" # Objective function to be used
verbosity: Null # Control the verbosity of the algorithm
